# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

cache:
  directories:
  - $HOME/.cache/pip
  - .eggs
  - .tox

env:
  matrix:
    - TOXENV=py36
    - TOXENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOXENV
